[package]
name = "rustrot13"
version = "0.1.0"
authors = ["SKP <skp.frl@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
